name: publish
on:
  push:
    branches:
      - 'publish'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: '"Build" the site'
        run: |
          cp -R src dist

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - uses: actions/deploy-pages@main
